// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pf_msg.proto

#include "pf_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace pf_msg {
class JobMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<JobMessage> _instance;
} _JobMessage_default_instance_;
class PrinterDataMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PrinterDataMessage> _instance;
} _PrinterDataMessage_default_instance_;
}  // namespace pf_msg
static void InitDefaultsJobMessage_pf_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pf_msg::_JobMessage_default_instance_;
    new (ptr) ::pf_msg::JobMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pf_msg::JobMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_JobMessage_pf_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsJobMessage_pf_5fmsg_2eproto}, {}};

static void InitDefaultsPrinterDataMessage_pf_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pf_msg::_PrinterDataMessage_default_instance_;
    new (ptr) ::pf_msg::PrinterDataMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pf_msg::PrinterDataMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PrinterDataMessage_pf_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPrinterDataMessage_pf_5fmsg_2eproto}, {}};

void InitDefaults_pf_5fmsg_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_JobMessage_pf_5fmsg_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PrinterDataMessage_pf_5fmsg_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_pf_5fmsg_2eproto[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_pf_5fmsg_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_pf_5fmsg_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_pf_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::pf_msg::JobMessage, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pf_msg::JobMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pf_msg::JobMessage, path_),
  PROTOBUF_FIELD_OFFSET(::pf_msg::JobMessage, encodedfile_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::pf_msg::PrinterDataMessage, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pf_msg::PrinterDataMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pf_msg::PrinterDataMessage, status_),
  PROTOBUF_FIELD_OFFSET(::pf_msg::PrinterDataMessage, printerid_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::pf_msg::JobMessage)},
  { 9, 16, sizeof(::pf_msg::PrinterDataMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::pf_msg::_JobMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pf_msg::_PrinterDataMessage_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_pf_5fmsg_2eproto = {
  {}, AddDescriptors_pf_5fmsg_2eproto, "pf_msg.proto", schemas,
  file_default_instances, TableStruct_pf_5fmsg_2eproto::offsets,
  file_level_metadata_pf_5fmsg_2eproto, 2, file_level_enum_descriptors_pf_5fmsg_2eproto, file_level_service_descriptors_pf_5fmsg_2eproto,
};

const char descriptor_table_protodef_pf_5fmsg_2eproto[] =
  "\n\014pf_msg.proto\022\006pf_msg\"/\n\nJobMessage\022\014\n\004"
  "path\030\001 \002(\t\022\023\n\013encodedFile\030\003 \002(\t\"\226\001\n\022Prin"
  "terDataMessage\0221\n\006status\030\001 \002(\0162!.pf_msg."
  "PrinterDataMessage.Status\022\021\n\tprinterId\030\002"
  " \001(\r\":\n\006Status\022\t\n\005NO_ID\020\000\022\013\n\007WAITING\020\001\022\014"
  "\n\010FINISHED\020\002\022\n\n\006FAILED\020\003"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_pf_5fmsg_2eproto = {
  false, InitDefaults_pf_5fmsg_2eproto, 
  descriptor_table_protodef_pf_5fmsg_2eproto,
  "pf_msg.proto", &assign_descriptors_table_pf_5fmsg_2eproto, 224,
};

void AddDescriptors_pf_5fmsg_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_pf_5fmsg_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_pf_5fmsg_2eproto = []() { AddDescriptors_pf_5fmsg_2eproto(); return true; }();
namespace pf_msg {
const ::google::protobuf::EnumDescriptor* PrinterDataMessage_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_pf_5fmsg_2eproto);
  return file_level_enum_descriptors_pf_5fmsg_2eproto[0];
}
bool PrinterDataMessage_Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const PrinterDataMessage_Status PrinterDataMessage::NO_ID;
const PrinterDataMessage_Status PrinterDataMessage::WAITING;
const PrinterDataMessage_Status PrinterDataMessage::FINISHED;
const PrinterDataMessage_Status PrinterDataMessage::FAILED;
const PrinterDataMessage_Status PrinterDataMessage::Status_MIN;
const PrinterDataMessage_Status PrinterDataMessage::Status_MAX;
const int PrinterDataMessage::Status_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void JobMessage::InitAsDefaultInstance() {
}
class JobMessage::HasBitSetters {
 public:
  static void set_has_path(JobMessage* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_encodedfile(JobMessage* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JobMessage::kPathFieldNumber;
const int JobMessage::kEncodedFileFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JobMessage::JobMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pf_msg.JobMessage)
}
JobMessage::JobMessage(const JobMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_path()) {
    path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.path_);
  }
  encodedfile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_encodedfile()) {
    encodedfile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.encodedfile_);
  }
  // @@protoc_insertion_point(copy_constructor:pf_msg.JobMessage)
}

void JobMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_JobMessage_pf_5fmsg_2eproto.base);
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  encodedfile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

JobMessage::~JobMessage() {
  // @@protoc_insertion_point(destructor:pf_msg.JobMessage)
  SharedDtor();
}

void JobMessage::SharedDtor() {
  path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  encodedfile_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JobMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const JobMessage& JobMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_JobMessage_pf_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void JobMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:pf_msg.JobMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      path_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      encodedfile_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* JobMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<JobMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required string path = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("pf_msg.JobMessage.path");
        object = msg->mutable_path();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // required string encodedFile = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("pf_msg.JobMessage.encodedFile");
        object = msg->mutable_encodedfile();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool JobMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pf_msg.JobMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string path = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->path().data(), static_cast<int>(this->path().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pf_msg.JobMessage.path");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string encodedFile = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_encodedfile()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->encodedfile().data(), static_cast<int>(this->encodedfile().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pf_msg.JobMessage.encodedFile");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pf_msg.JobMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pf_msg.JobMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void JobMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pf_msg.JobMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string path = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), static_cast<int>(this->path().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pf_msg.JobMessage.path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->path(), output);
  }

  // required string encodedFile = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->encodedfile().data(), static_cast<int>(this->encodedfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pf_msg.JobMessage.encodedFile");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->encodedfile(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pf_msg.JobMessage)
}

::google::protobuf::uint8* JobMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pf_msg.JobMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string path = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), static_cast<int>(this->path().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pf_msg.JobMessage.path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->path(), target);
  }

  // required string encodedFile = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->encodedfile().data(), static_cast<int>(this->encodedfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pf_msg.JobMessage.encodedFile");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->encodedfile(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pf_msg.JobMessage)
  return target;
}

size_t JobMessage::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:pf_msg.JobMessage)
  size_t total_size = 0;

  if (has_path()) {
    // required string path = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());
  }

  if (has_encodedfile()) {
    // required string encodedFile = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->encodedfile());
  }

  return total_size;
}
size_t JobMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pf_msg.JobMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string path = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());

    // required string encodedFile = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->encodedfile());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void JobMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pf_msg.JobMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const JobMessage* source =
      ::google::protobuf::DynamicCastToGenerated<JobMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pf_msg.JobMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pf_msg.JobMessage)
    MergeFrom(*source);
  }
}

void JobMessage::MergeFrom(const JobMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pf_msg.JobMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.path_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      encodedfile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.encodedfile_);
    }
  }
}

void JobMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pf_msg.JobMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JobMessage::CopyFrom(const JobMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pf_msg.JobMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JobMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void JobMessage::Swap(JobMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JobMessage::InternalSwap(JobMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  path_.Swap(&other->path_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  encodedfile_.Swap(&other->encodedfile_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata JobMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_pf_5fmsg_2eproto);
  return ::file_level_metadata_pf_5fmsg_2eproto[kIndexInFileMessages];
}


// ===================================================================

void PrinterDataMessage::InitAsDefaultInstance() {
}
class PrinterDataMessage::HasBitSetters {
 public:
  static void set_has_status(PrinterDataMessage* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_printerid(PrinterDataMessage* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PrinterDataMessage::kStatusFieldNumber;
const int PrinterDataMessage::kPrinterIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PrinterDataMessage::PrinterDataMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pf_msg.PrinterDataMessage)
}
PrinterDataMessage::PrinterDataMessage(const PrinterDataMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&status_, &from.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&printerid_) -
    reinterpret_cast<char*>(&status_)) + sizeof(printerid_));
  // @@protoc_insertion_point(copy_constructor:pf_msg.PrinterDataMessage)
}

void PrinterDataMessage::SharedCtor() {
  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&printerid_) -
      reinterpret_cast<char*>(&status_)) + sizeof(printerid_));
}

PrinterDataMessage::~PrinterDataMessage() {
  // @@protoc_insertion_point(destructor:pf_msg.PrinterDataMessage)
  SharedDtor();
}

void PrinterDataMessage::SharedDtor() {
}

void PrinterDataMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PrinterDataMessage& PrinterDataMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_PrinterDataMessage_pf_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void PrinterDataMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:pf_msg.PrinterDataMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&status_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&printerid_) -
        reinterpret_cast<char*>(&status_)) + sizeof(printerid_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* PrinterDataMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<PrinterDataMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required .pf_msg.PrinterDataMessage.Status status = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        if (!::pf_msg::PrinterDataMessage_Status_IsValid(val)) {
          ::google::protobuf::internal::WriteVarint(1, val, msg->mutable_unknown_fields());
          break;
        }
        msg->set_status(static_cast<::pf_msg::PrinterDataMessage_Status>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional uint32 printerId = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_printerid(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool PrinterDataMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pf_msg.PrinterDataMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .pf_msg.PrinterDataMessage.Status status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::pf_msg::PrinterDataMessage_Status_IsValid(value)) {
            set_status(static_cast< ::pf_msg::PrinterDataMessage_Status >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast<::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 printerId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_printerid(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &printerid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pf_msg.PrinterDataMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pf_msg.PrinterDataMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void PrinterDataMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pf_msg.PrinterDataMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .pf_msg.PrinterDataMessage.Status status = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }

  // optional uint32 printerId = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->printerid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pf_msg.PrinterDataMessage)
}

::google::protobuf::uint8* PrinterDataMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pf_msg.PrinterDataMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .pf_msg.PrinterDataMessage.Status status = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }

  // optional uint32 printerId = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->printerid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pf_msg.PrinterDataMessage)
  return target;
}

size_t PrinterDataMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pf_msg.PrinterDataMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .pf_msg.PrinterDataMessage.Status status = 1;
  if (has_status()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 printerId = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->printerid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PrinterDataMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pf_msg.PrinterDataMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const PrinterDataMessage* source =
      ::google::protobuf::DynamicCastToGenerated<PrinterDataMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pf_msg.PrinterDataMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pf_msg.PrinterDataMessage)
    MergeFrom(*source);
  }
}

void PrinterDataMessage::MergeFrom(const PrinterDataMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pf_msg.PrinterDataMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      status_ = from.status_;
    }
    if (cached_has_bits & 0x00000002u) {
      printerid_ = from.printerid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void PrinterDataMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pf_msg.PrinterDataMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrinterDataMessage::CopyFrom(const PrinterDataMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pf_msg.PrinterDataMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrinterDataMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void PrinterDataMessage::Swap(PrinterDataMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PrinterDataMessage::InternalSwap(PrinterDataMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(status_, other->status_);
  swap(printerid_, other->printerid_);
}

::google::protobuf::Metadata PrinterDataMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_pf_5fmsg_2eproto);
  return ::file_level_metadata_pf_5fmsg_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pf_msg
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::pf_msg::JobMessage* Arena::CreateMaybeMessage< ::pf_msg::JobMessage >(Arena* arena) {
  return Arena::CreateInternal< ::pf_msg::JobMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::pf_msg::PrinterDataMessage* Arena::CreateMaybeMessage< ::pf_msg::PrinterDataMessage >(Arena* arena) {
  return Arena::CreateInternal< ::pf_msg::PrinterDataMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
